<?php
declare(strict_types=1);

/**
 * LOVER LIPS YACHTS — initialize_env.php
 * One-shot production .env generator with self-destruct.
 *
 * PURPOSE
 *   Writes core/.env on the live Hostinger server without committing
 *   credentials to Git. Upload manually, run once, it deletes itself.
 *
 * WORKFLOW
 *   1. Upload this file to public_html/cockpit/ via Hostinger File Manager
 *      (it is intentionally excluded from the CI/CD pipeline).
 *   2. Open in browser (POST form shown on GET).
 *   3. Enter your INIT_TOKEN and DB_PASS, submit.
 *   4. Script writes core/.env, then unlink()s itself from disk.
 *
 * SECURITY CONTRACT
 *   • Token verified before any filesystem action.
 *   • DB_PASS accepted via POST body only — never in the URL.
 *   • Script self-destructs immediately after writing .env.
 *   • All other .env values are hardcoded to known production params.
 *
 * ⚠  NEVER commit this file with a real token hardcoded.
 *    Set INIT_TOKEN below to a strong random string before uploading.
 */

/* ── Edit this before uploading ───────────────────────────────────
   Generate with: php -r "echo bin2hex(random_bytes(24));"          */
define('INIT_TOKEN', 'REPLACE_WITH_A_STRONG_RANDOM_TOKEN_BEFORE_UPLOAD');

/* ── Hostinger fixed parameters ───────────────────────────────────
   These are known — only DB_PASS is entered at runtime.             */
define('DB_HOST_VAL', 'localhost');
define('DB_NAME_VAL', 'u713871298_lly_db');
define('DB_USER_VAL', 'u713871298_lly_db_user');

/* ── Self-destruct path ────────────────────────────────────────── */
define('SELF_PATH', __FILE__);
define('ENV_PATH',  __DIR__ . '/core/.env');

/* ─────────────────────────────────────────────────────────────────
   HANDLE POST — write .env and self-destruct
   ───────────────────────────────────────────────────────────────── */
if ($_SERVER['REQUEST_METHOD'] === 'POST') {

    header('Content-Type: text/plain; charset=utf-8');

    /* ── 1. Token verification ──────────────────────────────────── */
    $submittedToken = (string) ($_POST['init_token'] ?? '');
    if (INIT_TOKEN === 'REPLACE_WITH_A_STRONG_RANDOM_TOKEN_BEFORE_UPLOAD') {
        http_response_code(403);
        die('[!!] INIT_TOKEN has not been set. Edit the script before uploading.');
    }
    if ($submittedToken === '' || !hash_equals(INIT_TOKEN, $submittedToken)) {
        http_response_code(403);
        die('[!!] Invalid initialization token. Refusing to write .env.');
    }

    /* ── 2. Validate DB_PASS ────────────────────────────────────── */
    $dbPass = trim((string) ($_POST['db_pass'] ?? ''));
    if ($dbPass === '') {
        http_response_code(400);
        die('[!!] DB_PASS cannot be empty.');
    }
    if (strlen($dbPass) < 8) {
        http_response_code(400);
        die('[!!] DB_PASS is too short — minimum 8 characters.');
    }

    /* ── 3. Optional extras ─────────────────────────────────────── */
    $smtpPass  = trim((string) ($_POST['smtp_pass']  ?? ''));
    $diagToken = trim((string) ($_POST['diag_token'] ?? 'lly_diag_2026'));

    /* ── 4. Generate AI encryption key if not provided ──────────── */
    $aiKey = trim((string) ($_POST['ai_key'] ?? ''));
    if ($aiKey === '') {
        $aiKey = bin2hex(random_bytes(32));
    }

    /* ── 5. Build .env content ──────────────────────────────────── */
    $envContent = <<<ENV
; =============================================================================
; LOVER LIPS YACHTS — core/.env
; Generated by initialize_env.php on {$_SERVER['SERVER_NAME']}
; Written: {date('Y-m-d H:i:s T')}
; NEVER commit this file to Git.
; =============================================================================

; ─── ENTORNO ─────────────────────────────────────────────────────────────────
APP_ENV="production"
APP_VERSION="2.0.0"

; ─── URLs ────────────────────────────────────────────────────────────────────
APP_URL_LOCAL="http://localhost/loverlipsyachts"
APP_URL_PRODUCTION="https://loverlipsyachts.com"
APP_COCKPIT_URL="https://loverlipsyachts.com/cockpit/"

; ─── BASE DE DATOS MYSQL — Production (Hostinger / loverlipsyachts.com) ─────
DB_HOST="localhost"
DB_NAME="u713871298_lly_db"
DB_USER="u713871298_lly_db_user"
DB_PASS="{$dbPass}"

; ─── FTP — Production (Hostinger) ────────────────────────────────────────────
FTP_HOST="ftp.loverlipsyachts.com"
FTP_PORT="21"
FTP_USER="u713871298.llyftpuser"
FTP_SECURE="EXPLICIT"

; ─── RUTAS EN EL SERVIDOR REMOTO ─────────────────────────────────────────────
REMOTE_ROOT="/public_html/cockpit"
REMOTE_CORE="/public_html/cockpit/core"
REMOTE_ASSETS="/public_html/cockpit/assets"
REMOTE_BOOK="/public_html/my-book"

; ─── CORS / ORÍGENES PERMITIDOS ──────────────────────────────────────────────
ALLOWED_ORIGINS="https://loverlipsyachts.com,http://localhost,http://localhost:8080"

; ─── SMTP ────────────────────────────────────────────────────────────────────
SMTP_HOST="mail.loverlipsyachts.com"
SMTP_PORT="465"
SMTP_USER="no-reply@loverlipsyachts.com"
SMTP_PASS="{$smtpPass}"
SMTP_FROM_EMAIL="no-reply@loverlipsyachts.com"
SMTP_FROM_NAME="Lover Lips Yachts"

; ─── SEGURIDAD ───────────────────────────────────────────────────────────────
AI_ENCRYPTION_KEY="{$aiKey}"

DIAG_TOKEN={$diagToken}
ENV;

    /* Replace the placeholder {date()} since heredoc doesn't call functions */
    $envContent = str_replace(
        '{date(\'Y-m-d H:i:s T\')}',
        date('Y-m-d H:i:s T'),
        $envContent
    );

    /* ── 6. Verify core/ directory exists ───────────────────────── */
    $coreDir = __DIR__ . '/core';
    if (!is_dir($coreDir)) {
        die('[!!] core/ directory not found at: ' . $coreDir . "\nDeploy the full cockpit package first.");
    }
    if (!is_writable($coreDir)) {
        die('[!!] core/ directory is not writable. Check Hostinger file permissions (755).');
    }

    /* ── 7. Write .env atomically ───────────────────────────────── */
    $tmpPath = $coreDir . '/.env_tmp_' . bin2hex(random_bytes(8));
    $written = file_put_contents($tmpPath, $envContent, LOCK_EX);

    if ($written === false) {
        @unlink($tmpPath);
        die('[!!] Failed to write .env — check write permissions on core/.');
    }

    if (!rename($tmpPath, ENV_PATH)) {
        @unlink($tmpPath);
        die('[!!] Atomic rename failed. Manual cleanup: delete ' . $tmpPath);
    }

    /* ── 8. Verify the written file ─────────────────────────────── */
    if (!file_exists(ENV_PATH) || filesize(ENV_PATH) < 100) {
        die('[!!] .env was written but appears too small — verify manually.');
    }

    /* ── 9. Self-destruct ───────────────────────────────────────── */
    $selfDeleted = @unlink(SELF_PATH);

    /* ── 10. Success output ─────────────────────────────────────── */
    echo "[OK]  core/.env written successfully.\n";
    echo "[--]  Path    : " . ENV_PATH . "\n";
    echo "[--]  Size    : " . filesize(ENV_PATH) . " bytes\n";
    echo "[--]  DB_NAME : " . DB_NAME_VAL . "\n";
    echo "[--]  DB_USER : " . DB_USER_VAL . "\n";
    echo "[--]  DB_PASS : [REDACTED — " . strlen($dbPass) . " chars]\n\n";

    if ($selfDeleted) {
        echo "[OK]  initialize_env.php has been deleted from the server.\n";
        echo "[--]  Run test_infra.php?token=YOUR_TOKEN to verify connectivity.\n";
    } else {
        echo "[!!]  WARNING: Self-destruct failed — manually delete initialize_env.php\n";
        echo "[--]  Path: " . SELF_PATH . "\n";
    }

    exit(0);
}

/* ─────────────────────────────────────────────────────────────────
   HANDLE GET — show the secure form
   ───────────────────────────────────────────────────────────────── */
?><!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>LLY — Initialize Production Environment</title>
  <link rel="stylesheet" href="assets/css/style.css">
</head>
<body data-active-lang="en">

  <header class="topbar" role="banner">
    <div class="container">
      <div class="topbar-inner">
        <div class="topbar-brand">
          Lover Lips Yachts
          <span>Environment Setup</span>
        </div>
      </div>
    </div>
  </header>

  <main>
    <section class="section section-white" aria-labelledby="setup-title">
      <div class="container">

        <p class="section-label">One-Shot Utility · Self-Destructs After Use</p>
        <h1 class="section-title" id="setup-title">
          Production Environment <em>Initializer</em>
        </h1>
        <p class="section-subtitle">
          This form writes <code>core/.env</code> on the live Hostinger server and
          then deletes itself permanently. Enter your credentials below and submit once.
        </p>

        <?php if (INIT_TOKEN === 'REPLACE_WITH_A_STRONG_RANDOM_TOKEN_BEFORE_UPLOAD'): ?>
        <div class="editor-alert editor-alert--error" role="alert">
          ⚠ INIT_TOKEN has not been set in this script. Edit the constant at the top of
          initialize_env.php before uploading to production.
        </div>
        <?php endif; ?>

        <form method="POST" action="" class="editor-form" autocomplete="off">

          <fieldset class="editor-fieldset">
            <legend class="editor-legend">
              <span class="editor-legend-icon">🔐</span>
              Authorization
            </legend>
            <div class="editor-field">
              <label class="editor-label" for="init_token">Initialization Token</label>
              <input type="password" id="init_token" name="init_token"
                     class="editor-input" required
                     placeholder="Enter the token set inside this script" />
            </div>
          </fieldset>

          <fieldset class="editor-fieldset editor-fieldset--highlight">
            <legend class="editor-legend">
              <span class="editor-legend-icon">🗄️</span>
              Database Credentials
            </legend>
            <div class="editor-field">
              <label class="editor-label" for="db_name_display">DB Name (fixed)</label>
              <input type="text" id="db_name_display" class="editor-input"
                     value="<?= htmlspecialchars(DB_NAME_VAL, ENT_QUOTES, 'UTF-8') ?>"
                     readonly />
            </div>
            <div class="editor-field">
              <label class="editor-label" for="db_user_display">DB User (fixed)</label>
              <input type="text" id="db_user_display" class="editor-input"
                     value="<?= htmlspecialchars(DB_USER_VAL, ENT_QUOTES, 'UTF-8') ?>"
                     readonly />
            </div>
            <div class="editor-field">
              <label class="editor-label" for="db_pass">DB Password (from Hostinger hPanel)</label>
              <input type="password" id="db_pass" name="db_pass"
                     class="editor-input" required
                     placeholder="Paste your Hostinger MySQL password" />
            </div>
          </fieldset>

          <fieldset class="editor-fieldset">
            <legend class="editor-legend">
              <span class="editor-legend-icon">⚙️</span>
              Optional Parameters
            </legend>
            <div class="editor-field">
              <label class="editor-label" for="smtp_pass">SMTP Password (leave blank to skip)</label>
              <input type="password" id="smtp_pass" name="smtp_pass"
                     class="editor-input"
                     placeholder="Hostinger SMTP / mail password" />
            </div>
            <div class="editor-field">
              <label class="editor-label" for="diag_token">Diagnostic Token for test_infra.php</label>
              <input type="text" id="diag_token" name="diag_token"
                     class="editor-input"
                     value="lly_diag_2026"
                     placeholder="lly_diag_2026" />
            </div>
          </fieldset>

          <div class="editor-publish-bar">
            <span class="editor-publish-note">
              This script deletes itself the moment .env is written successfully.
            </span>
            <button type="submit" class="editor-publish-btn">
              <span>🚀 Write core/.env &amp; Self-Destruct</span>
            </button>
          </div>

        </form>

      </div>
    </section>
  </main>

</body>
</html>
